-- MySQL Script generated by MySQL Workbench
-- Sat Dec  6 17:47:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema do2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema do2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `do2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `do2` ;

-- -----------------------------------------------------
-- Table `do2`.`deadline_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `do2`.`deadline_task` ;

CREATE TABLE IF NOT EXISTS `do2`.`deadline_task` (
  `task_id` INT NOT NULL,
  `due_datetime` DATETIME(1) NOT NULL,
  PRIMARY KEY (`task_id`),
  UNIQUE INDEX `task_id_UNIQUE` (`task_id` ASC) VISIBLE,
  INDEX `task_idx` (`task_id` ASC) VISIBLE,
  CONSTRAINT `deadline_task_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `do2`.`task` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `do2`.`settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `do2`.`settings` ;

CREATE TABLE IF NOT EXISTS `do2`.`settings` (
  `user_email` VARCHAR(254) NOT NULL,
  `theme` ENUM('light', 'dark') NOT NULL DEFAULT 'light',
  `time_to_delete` INT NOT NULL,
  PRIMARY KEY (`user_email`),
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC) VISIBLE,
  CONSTRAINT `settings_user`
    FOREIGN KEY (`user_email`)
    REFERENCES `do2`.`user` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `do2`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `do2`.`tag` ;

CREATE TABLE IF NOT EXISTS `do2`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `color` CHAR(7) NOT NULL,
  `name` VARCHAR(32) CHARACTER SET 'utf8mb3' NOT NULL,
  `user_email` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `tag_user_idx` (`user_email` ASC) VISIBLE,
  CONSTRAINT `tag_user`
    FOREIGN KEY (`user_email`)
    REFERENCES `do2`.`user` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `do2`.`tagged_by`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `do2`.`tagged_by` ;

CREATE TABLE IF NOT EXISTS `do2`.`tagged_by` (
  `task_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`task_id`, `tag_id`),
  INDEX `task_idx` (`task_id` ASC) VISIBLE,
  INDEX `tagged_by_tag` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `tagged_by_tag`
    FOREIGN KEY (`tag_id`)
    REFERENCES `do2`.`tag` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tagged_by_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `do2`.`task` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `do2`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `do2`.`task` ;

CREATE TABLE IF NOT EXISTS `do2`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_pinned` TINYINT(1) NOT NULL DEFAULT '0',
  `is_done` TINYINT(1) NOT NULL DEFAULT '0',
  `name` VARCHAR(32) CHARACTER SET 'utf8mb3' NOT NULL,
  `datetime_to_delete` DATETIME(1) NULL DEFAULT NULL,
  `description` VARCHAR(140) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `supertask_id` INT NULL DEFAULT NULL,
  `user_email` VARCHAR(254) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `Supertask_idx` (`supertask_id` ASC) VISIBLE,
  INDEX `user_idx` (`user_email` ASC) VISIBLE,
  CONSTRAINT `task_supertask`
    FOREIGN KEY (`supertask_id`)
    REFERENCES `do2`.`task` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `task_user`
    FOREIGN KEY (`user_email`)
    REFERENCES `do2`.`user` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 96
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `do2`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `do2`.`user` ;

CREATE TABLE IF NOT EXISTS `do2`.`user` (
  `email` VARCHAR(254) NOT NULL,
  `password_hash` BINARY(128) NOT NULL,
  `password_salt` BINARY(32) NOT NULL,
  `first_name` VARCHAR(32) CHARACTER SET 'utf8mb3' NOT NULL,
  `last_name` VARCHAR(32) CHARACTER SET 'utf8mb3' NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
